{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Anil\\AppData\\Local\\Temp\\ipykernel_4584\\1200658067.py\", line 25, in translate\n",
      "    output = translator.translate(lang_1, dest=cl)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\client.py\", line 182, in translate\n",
      "    data = self._translate(text, dest, src, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\client.py\", line 78, in _translate\n",
      "    token = self.token_acquirer.do(text)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\gtoken.py\", line 194, in do\n",
      "    self._update()\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\gtoken.py\", line 54, in _update\n",
      "    r = self.client.get(self.host)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 755, in get\n",
      "    return self.request(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 600, in request\n",
      "    return self.send(\n",
      "           ^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 620, in send\n",
      "    response = self.send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 647, in send_handling_redirects\n",
      "    response = self.send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 684, in send_handling_auth\n",
      "    response = self.send_single_request(request, timeout)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 714, in send_single_request\n",
      "    ) = transport.request(\n",
      "        ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection_pool.py\", line 152, in request\n",
      "    response = connection.request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection.py\", line 65, in request\n",
      "    self.socket = self._open_socket(timeout)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection.py\", line 85, in _open_socket\n",
      "    return self.backend.open_tcp_stream(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_backends\\sync.py\", line 133, in open_tcp_stream\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"c:\\Python311\\Lib\\contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_exceptions.py\", line 12, in map_exceptions\n",
      "    raise to_exc(exc) from None\n",
      "httpcore._exceptions.ConnectError: [Errno 11001] getaddrinfo failed\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Anil\\AppData\\Local\\Temp\\ipykernel_4584\\1200658067.py\", line 25, in translate\n",
      "    output = translator.translate(lang_1, dest=cl)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\client.py\", line 182, in translate\n",
      "    data = self._translate(text, dest, src, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\client.py\", line 78, in _translate\n",
      "    token = self.token_acquirer.do(text)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\gtoken.py\", line 194, in do\n",
      "    self._update()\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\gtoken.py\", line 54, in _update\n",
      "    r = self.client.get(self.host)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 755, in get\n",
      "    return self.request(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 600, in request\n",
      "    return self.send(\n",
      "           ^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 620, in send\n",
      "    response = self.send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 647, in send_handling_redirects\n",
      "    response = self.send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 684, in send_handling_auth\n",
      "    response = self.send_single_request(request, timeout)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 714, in send_single_request\n",
      "    ) = transport.request(\n",
      "        ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection_pool.py\", line 152, in request\n",
      "    response = connection.request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection.py\", line 65, in request\n",
      "    self.socket = self._open_socket(timeout)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection.py\", line 85, in _open_socket\n",
      "    return self.backend.open_tcp_stream(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_backends\\sync.py\", line 133, in open_tcp_stream\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"c:\\Python311\\Lib\\contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_exceptions.py\", line 12, in map_exceptions\n",
      "    raise to_exc(exc) from None\n",
      "httpcore._exceptions.ConnectError: [Errno 11001] getaddrinfo failed\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Anil\\AppData\\Local\\Temp\\ipykernel_4584\\1200658067.py\", line 25, in translate\n",
      "    output = translator.translate(lang_1, dest=cl)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\client.py\", line 182, in translate\n",
      "    data = self._translate(text, dest, src, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\client.py\", line 78, in _translate\n",
      "    token = self.token_acquirer.do(text)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\gtoken.py\", line 194, in do\n",
      "    self._update()\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\gtoken.py\", line 54, in _update\n",
      "    r = self.client.get(self.host)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 755, in get\n",
      "    return self.request(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 600, in request\n",
      "    return self.send(\n",
      "           ^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 620, in send\n",
      "    response = self.send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 647, in send_handling_redirects\n",
      "    response = self.send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 684, in send_handling_auth\n",
      "    response = self.send_single_request(request, timeout)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 714, in send_single_request\n",
      "    ) = transport.request(\n",
      "        ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection_pool.py\", line 152, in request\n",
      "    response = connection.request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection.py\", line 65, in request\n",
      "    self.socket = self._open_socket(timeout)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection.py\", line 85, in _open_socket\n",
      "    return self.backend.open_tcp_stream(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_backends\\sync.py\", line 133, in open_tcp_stream\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"c:\\Python311\\Lib\\contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_exceptions.py\", line 12, in map_exceptions\n",
      "    raise to_exc(exc) from None\n",
      "httpcore._exceptions.ConnectError: [Errno 11001] getaddrinfo failed\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python311\\Lib\\tkinter\\__init__.py\", line 1948, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Anil\\AppData\\Local\\Temp\\ipykernel_4584\\1200658067.py\", line 25, in translate\n",
      "    output = translator.translate(lang_1, dest=cl)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\client.py\", line 182, in translate\n",
      "    data = self._translate(text, dest, src, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\client.py\", line 78, in _translate\n",
      "    token = self.token_acquirer.do(text)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\gtoken.py\", line 194, in do\n",
      "    self._update()\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\googletrans\\gtoken.py\", line 54, in _update\n",
      "    r = self.client.get(self.host)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 755, in get\n",
      "    return self.request(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 600, in request\n",
      "    return self.send(\n",
      "           ^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 620, in send\n",
      "    response = self.send_handling_redirects(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 647, in send_handling_redirects\n",
      "    response = self.send_handling_auth(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 684, in send_handling_auth\n",
      "    response = self.send_single_request(request, timeout)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpx\\_client.py\", line 714, in send_single_request\n",
      "    ) = transport.request(\n",
      "        ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection_pool.py\", line 152, in request\n",
      "    response = connection.request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection.py\", line 65, in request\n",
      "    self.socket = self._open_socket(timeout)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_sync\\connection.py\", line 85, in _open_socket\n",
      "    return self.backend.open_tcp_stream(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_backends\\sync.py\", line 133, in open_tcp_stream\n",
      "    with map_exceptions(exc_map):\n",
      "  File \"c:\\Python311\\Lib\\contextlib.py\", line 155, in __exit__\n",
      "    self.gen.throw(typ, value, traceback)\n",
      "  File \"c:\\Python311\\Lib\\site-packages\\httpcore\\_exceptions.py\", line 12, in map_exceptions\n",
      "    raise to_exc(exc) from None\n",
      "httpcore._exceptions.ConnectError: [Errno 11001] getaddrinfo failed\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk \n",
    "from tkinter import * \n",
    "from tkinter import ttk\n",
    "from googletrans import Translator\n",
    "from tkinter import messagebox\n",
    "\n",
    "root = tk.Tk()\n",
    "root.title('Language Translator')\n",
    "root.geometry('590x370')\n",
    "\n",
    "frame1 = Frame(root, width=590, height=370, relief=RIDGE, borderwidth=5, bg='#1d1d1d')\n",
    "frame1.place(x=0, y=0)\n",
    "\n",
    "Label(root, text=\"Language Translator\", font=(\"Helvetica 20 bold\"), fg=\"white\", bg='#1d1d1d').pack(pady=10)\n",
    "\n",
    "def translate():\n",
    "    lang_1= text_entry1.get(\"1.0\", \"end-1c\")\n",
    "    cl = choose_language.get()\n",
    "\n",
    "    if lang_1 == '':\n",
    "        messagebox.showerror('Language Translator', 'Enter the text to translate!')\n",
    "    else:\n",
    "        text_entry2.delete(1.0, 'end')\n",
    "        translator = Translator()\n",
    "        output = translator.translate(lang_1, dest=cl)\n",
    "        text_entry2.insert('end', output.text)\n",
    "\n",
    "def clear():\n",
    "    text_entry1.delete(1.0, 'end')\n",
    "    text_entry2.delete(1.0, 'end')\n",
    "\n",
    "a = tk.StringVar()\n",
    "\n",
    "auto_select = ttk.Combobox(frame1, width=27, textvariable=a, state='randomly', font=('verdana', 10, 'bold'))\n",
    "\n",
    "auto_select['values'] = (\n",
    "                            'Auto Select',\n",
    "                        )\n",
    "\n",
    "auto_select.place(x=15, y=60)\n",
    "auto_select.current(0)\n",
    "\n",
    "l = tk.StringVar()\n",
    "choose_language = ttk.Combobox(frame1, width=27, textvariable=l, state='randomly', font=('verdana', 10, 'bold'))\n",
    "\n",
    "choose_language['values'] = (\n",
    "                                \"English\",\n",
    "                                \"French\",\n",
    "                                \"Hindi\",\n",
    "                                \"Japanese\",\n",
    "                                \"Arabic\",\n",
    "                                \"Greece\"\n",
    "                                \"Spanish\",\n",
    "                                \"German\",\n",
    "                                \"Portuguese\",\n",
    "                                \"Russian\",\n",
    "                                \"Bengali\",\n",
    "                                \"Korean\",\n",
    "                                \"Italian\",\n",
    "                                \"Urdu\",\n",
    "                                \"Chinese\",\n",
    "                                \"Gujarati\",\n",
    "                                \"Tamil\",\n",
    "                                \"Marathi\",\n",
    "                                \"Turkish\",\n",
    "                                \"Indonesian\",\n",
    "                                \"Kannada\",\n",
    "                                \"Telugu\",\n",
    "                                \"Dutch\",\n",
    "                                \"Danish\",\n",
    "                                \"Vietnamese\"\n",
    "                            )\n",
    "\n",
    "choose_language.place(x=305, y=60)\n",
    "choose_language.current(0)\n",
    "\n",
    "text_entry1 = Text(frame1, width=20, height=7, borderwidth=5, relief=RIDGE, font=('verdana', 15))\n",
    "text_entry1.place(x=10, y=100)\n",
    "\n",
    "text_entry2 = Text(frame1, width=20, height=7, borderwidth=5, relief=RIDGE, font=('verdana', 15))\n",
    "text_entry2.place(x=300, y=100)\n",
    "\n",
    "btn1 = Button(frame1, command=translate, text=\"Translate\", relief=RAISED, borderwidth=2, font=('verdana', 10, 'bold'), bg='#248aa2', fg=\"white\", cursor=\"hand2\")\n",
    "btn1.place(x=185, y=300)\n",
    "\n",
    "btn2 = Button(frame1, command=clear, text=\"Clear\", relief=RAISED, borderwidth=2, font=('verdana', 10, 'bold'), bg='#248aa2', fg=\"white\", cursor=\"hand2\")\n",
    "btn2.place(x=300, y=300)\n",
    "\n",
    "root.mainloop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
